
const licenciaturas = [
  "Antropologia",
  "Arquitetura",
  "Ciência de Dados",
  "Ciência Política",
  "Economia",
  "Engenharia Informática",
  "Engenharia de Telecomunicações e Informática",
  "Finanças e Contabilidade",
  "Gestão",
  "Gestão Industrial e Logística",
  "Gestão de Marketing",
  "Gestão de Recursos Humanos",
  "História Moderna e Contemporânea",
  "Informática e Gestão de Empresas",
  "Psicologia",
  "Serviço Social",
  "Sociologia",
  "Desenvolvimento de Software e Aplicações",
  "Matemática Aplicada e Tecnologias Digitais",
  "Política, Economia e Sociedade",
  "Tecnologias Digitais e Automação",
  "Tecnologias Digitais, Edifícios e Construção Sustentável",
  "Tecnologias Digitais Educativas",
  "Tecnologias Digitais e Gestão",
  "Tecnologias Digitais e Inteligência Artificial",
  "Tecnologias Digitais e Saúde",
  "Tecnologias Digitais e Segurança de Informação"
];

const mestrados = [
  "Ação Humanitária",
  "Administração Escolar",
  "Administração Pública",
  "Antropologia",
  "Arquitetura e Cultura Visual em Lisboa",
  "Ciência de Dados",
  "Ciência Política",
  "Ciências das Emoções",
  "Comunicação, Cultura e Tecnologias da Informação",
  "Conservação e Reabilitação Sustentável",
  "Contabilidade e Controlo de Gestão",
  "Desenvolvimento de Turismo e Cultura (Erasmus Mundus)",
  "Digitalização na Administração Pública",
  "Direito das Empresas e do Trabalho",
  "Economia",
  "Economia da Empresa e da Concorrência",
  "Economia e Políticas Públicas",
  "Economia Monetária e Financeira",
  "Economia Política",
  "Economia Social e Solidária",
  "Educação e Sociedade",
  "Engenharia de Telecomunicações e Informática",
  "Engenharia Informática",
  "Estudos Africanos",
  "Estudos Chineses",
  "Estudos da Deficiência e Direitos Humanos",
  "Estudos de Desenvolvimento",
  "Estudos e Gestão da Cultura",
  "Estudos Internacionais",
  "Estudos Sociais do Ambiente e da Sustentabilidade",
  "Estudos Urbanos",
  "Finanças",
  "Gestão",
  "Gestão Aplicada",
  "Gestão Aplicada em Saúde",
  "Gestão de Empresas",
  "Gestão de Hotelaria e Turismo",
  "Gestão de Novos Media",
  "Gestão de Recursos Humanos e Consultadoria Organizacional",
  "Gestão de Serviços de Saúde",
  "Gestão de Serviços e da Tecnologia",
  "Gestão de Sistemas de Informação",
  "Gestão Internacional",
  "Governação e Sustentabilidade do Mar",
  "História Moderna e Contemporânea",
  "Informática e Gestão",
  "Inovação Digital para Práticas de Projeto",
  "Inteligência Artificial",
  "Marketing",
  "Matemática Financeira",
  "Mercados da Arte",
  "Métodos Analíticos para Gestão",
  "Políticas de Desenvolvimento dos Recursos Humanos",
  "Políticas Públicas",
  "Psicologia Comunitária, Proteção de Crianças e Jovens em Risco",
  "Psicologia da Mobilidade Global, Inclusão e Diversidade na Sociedade - Erasmus Mundus",
  "Psicologia das Relações Interculturais",
  "Psicologia Social da Saúde",
  "Psicologia Social e das Organizações",
  "Serviço Social",
  "Serviço Social com Crianças e Jovens (Erasmus Mundus)",
  "Serviço Social com Famílias e Crianças (Erasmus Mundus)",
  "Sistemas Integrados de Apoio à Decisão",
  "Sociologia",
  "Software de Código Aberto",
  "Tecnologias Digitais para o Negócio",
  "Trabalho, Emprego e Sociedade",
  "Ciências do Trabalho e Relações Laborais (a cessar)",
  "Estudos de Internet (a cessar)",
  "Estudos do Ambiente e da Sustentabilidade (a cessar)"
];

const doutoramentos = [
  "Antropologia",
  "Antropologia: Políticas e Imagens da Cultura e Museologia",
  "Arquitetura dos Territórios Metropolitanos Contemporâneos",
  "Ciência Política",
  "Ciências da Complexidade",
  "Ciências da Comunicação",
  "Ciências e Tecnologias da Informação",
  "Economia",
  "Economia Política, Doutoramento Interdisciplinar",
  "Estudos Africanos",
  "Estudos Internacionais",
  "Estudos Urbanos",
  "Finanças",
  "Gestão",
  "Gestão Empresarial Aplicada",
  "História Moderna e Contemporânea",
  "História, Estudos de Segurança e Defesa",
  "História: mudança e continuidade num mundo global",
  "Políticas de Administração e Gestão Escolar",
  "Políticas Públicas",
  "Psicologia",
  "Serviço Social",
  "Sociologia",
  "Transições para a Sustentabilidade",
  "Gestão do Turismo (a cessar)"
];

// Gera lista única com tipo entre parêntesis
const cursosComTipo = [
  ...licenciaturas.map(curso => `${curso} (Licenciatura)`),
  ...mestrados.map(curso => `${curso} (Mestrado)`),
  ...doutoramentos.map(curso => `${curso} (Doutoramento)`)
];

module.exports = {
  licenciaturas,
  mestrados,
  doutoramentos,
  cursosComTipo
};