const mongoose = require("mongoose");


// Lista de UCs únicas do ISCTE Licenciaturas
const ucsUnicas = [
  "",
  "Problemáticas Centrais da Reflexão Antropológica",
  "História da Antropologia",
  "Práticas de Trabalho Universitário",
  "Métodos Etnográficos e Práticas de Investigação",
  "Epistemologia e Conhecimento Antropológico",
  "Culturas: Identificações e Diferenciações",
  "Ciência, Sociedade e Cultura",
  "Escrita de Textos Técnicos e Científicos",
  "Métodos e Técnicas de Estudo",
  "Introdução ao Excel",
  "Mapas Etnográficos 1: Américas e África",
  "Mapas Etnográficos 2: Ásia e Oceania",
  "Métodos Biográficos",
  "Colonialismo, Pós‑Colonialismo e Antropologia",
  "Leituras Etnográficas",
  "Símbolos: Linguagem, Ação e Cognição",
  "Relações: Géneros, Famílias, Parentesco",
  "Poderes: o Económico e o Político",
  "Debates Teóricos Contemporâneos",
  "Práticas Profissionais de Antropologia",
  "Etnografia Portuguesa",
  "Antropologia e Imagem",
  "Estágio Curricular",
  "Cultura Arquitetónica",
  "Teoria e História da Arquitetura",
  "Desenho I",
  "Fundamentos de Física para Arquitetura",
  "Geografia I",
  "Desenho II",
  "Arquitetura I",
  "Arquitetura II",
  "Geografia II",
  "Arquitetura III",
  "Arquitetura IV",
  "Desenho III",
  "Sistemas de Construção I",
  "Sistemas de Construção II",
  "Tecnologia da Arquitetura",
  "Projeto Final de Arquitetura",
  "Representação Digital",
  "Ambiente e Sustentabilidade",
  "Estética e Filosofia da Arquitetura",
  "Planeamento Urbano",
  "Seminário de Projeto I",
  "Seminário de Projeto II",
  "Matemática Discreta",
  "Álgebra Linear",
  "Cálculo Diferencial e Integral",
  "Estatística Descritiva",
  "Probabilidades",
  "Análise Exploratória de Dados",
  "Programação em Python",
  "Fundamentos de Programação",
  "Estruturas de Dados",
  "Bases de Dados",
  "Visualização de Dados",
  "Introdução à Ciência de Dados",
  "Aprendizagem Automática",
  "Big Data",
  "Processamento de Linguagem Natural",
  "Mineração de Dados",
  "Inteligência Artificial",
  "Ética e Privacidade em Dados",
  "Projeto Integrador em Ciência de Dados",
  "Gestão de Projetos de Dados",
  "Introdução à Ciência Política",
  "Teoria Política",
  "Sistemas Políticos Contemporâneos",
  "Comportamento Político",
  "Administração Pública",
  "Política Comparada",
  "Política Internacional",
  "Métodos e Técnicas de Investigação",
  "Políticas Públicas",
  "Direito Constitucional",
  "Análise de Políticas Públicas",
  "Democracia e Cidadania",
  "Partidos e Sistemas Partidários",
  "Género e Política",
  "Comunicação Política",
  "Tópicos de Ciência Política",
  "Geopolítica",
  "Ética Política",
  "Projeto Final em Ciência Política",
  "Microeconomia",
  "Macroeconomia",
  "Economia Portuguesa e Europeia",
  "Economia Internacional",
  "História Económica e Social",
  "Teoria dos Jogos",
  "Economia Pública",
  "Economia do Trabalho",
  "Economia da Inovação",
  "Economia do Ambiente",
  "Política Económica",
  "Econometria",
  "Estatística",
  "Matemática",
  "Contabilidade",
  "Gestão",
  "Direito Empresarial",
  "Projeto em Economia",
  "Introdução à Programação",
  "Algoritmos e Estruturas de Dados",
  "Arquitetura de Computadores",
  "Sistemas Operativos",
  "Redes de Computadores",
  "Programação Orientada a Objetos",
  "Engenharia de Software",
  "Computação Móvel",
  "Computação em Nuvem",
  "Segurança Informática",
  "Projeto Final em Engenharia Informática",
  "Projeto em Engenharia Informática",
  "Interação Humano-Computador",
  "Análise e Projeto de Sistemas",
  "Programação Web",
  "Desenvolvimento de Aplicações",
  "Gestão de Sistemas de Informação",
  "Sistemas Distribuídos",
  "Empreendedorismo e Inovação",
  "Introdução à Psicologia",
  "Psicologia do Desenvolvimento",
  "Psicologia Social",
  "Psicologia Cognitiva",
  "Neuropsicologia",
  "Psicopatologia",
  "Psicologia Clínica",
  "Psicologia da Educação",
  "Métodos de Investigação em Psicologia",
  "Psicometria",
  "Intervenção Psicológica",
  "Estágio em Psicologia",
  "Ética e Deontologia Profissional",
  "Tecnologias e Sociedade",
  "Cidadania Digital",
  "Tecnologias Emergentes",
  "Fundamentos de Robótica",
  "Internet das Coisas",
  "Automação e Controlo",
  "Redes Industriais",
  "Sistemas Embarcados",
  "Computação Física",
  "Projeto Integrador em Tecnologias",
  "Complementos de Matemática",
  "Tópicos de Física Aplicada",
  "Estágio em Tecnologias",
  "Seminário de Inovação Tecnológica",
  "Projeto em Engenharia Informática",
  "Interação Humano-Computador",
  "Análise e Projeto de Sistemas",
  "Programação Web",
  "Desenvolvimento de Aplicações",
  "Gestão de Sistemas de Informação",
  "Sistemas Distribuídos",
  "Empreendedorismo e Inovação",
  "Introdução à Psicologia",
  "Psicologia do Desenvolvimento",
  "Psicologia Social",
  "Psicologia Cognitiva",
  "Neuropsicologia",
  "Psicopatologia",
  "Psicologia Clínica",
  "Psicologia da Educação",
  "Métodos de Investigação em Psicologia",
  "Psicometria",
  "Intervenção Psicológica",
  "Estágio em Psicologia",
  "Ética e Deontologia Profissional",
  "Tecnologias e Sociedade",
  "Cidadania Digital",
  "Tecnologias Emergentes",
  "Fundamentos de Robótica",
  "Internet das Coisas",
  "Automação e Controlo",
  "Redes Industriais",
  "Sistemas Embarcados",
  "Computação Física",
  "Projeto Integrador em Tecnologias",
  "Complementos de Matemática",
  "Tópicos de Física Aplicada",
  "Estágio em Tecnologias",
  "Seminário de Inovação Tecnológica",
  "Matemática para Gestão",
  "Métodos e Técnicas de Investigação",
  "Ética e Privacidade em Dados",
  "Direito e Políticas Sociais",
  "Fundamentos das Ciências Sociais",
  "História das Ideias Políticas",
  "História Económica e Social",
  "Fundamentos de Programação",
  "Estatística e Probabilidades",
  "Projeto Final",
  "Gestão de Projetos",
  "Gestão de Equipas",
  "Economia da Empresa",
  "Direito Empresarial",
  "Tecnologias de Informação",
  "Comportamento Organizacional",
  "Economia Portuguesa e Europeia",
  "Gestão da Inovação",
  "Sistemas Dinâmicos",
  "Tecnologias de Apoio à Decisão"
];

module.exports = {
  ucsUnicas
};
